language: objective-c
osx_image: xcode7
xcode_project: YMCache.xcodeproj
xcode_scheme: YMCache-iOS
before_install:
- brew update || brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
- gem install slather --no-rdoc --no-ri --no-document --quiet
- "./script/travis-codesign-setup.sh"
install:
- carthage bootstrap
after_install:
- "./script/travis-codesign-teardown.sh"
script:
- xcodebuild clean test -project YMCache.xcodeproj -scheme YMCache-iOS -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  | xcpretty -c -f `xcpretty-travis-formatter`
- set -o pipefail && xcodebuild clean test -project YMCache.xcodeproj -scheme YMCache-Mac
  -sdk macosx ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  | xcpretty -c -f `xcpretty-travis-formatter`
- pod lib lint --quick
after_success:
- slather
env:
  global:
  # Coveralls API Key
  - secure: XjmvN8ABJy19pzTQtCnbi8PKei+fJ8m20LU2cuNEDP3LfTwt34tVtYGNaI4YTEiPpEvKTSWQpRUUQWzw3l2AyY6ia282URtxYXi3lSlH2WW0zjqkueWlFDCnrTeuv+DLQVE1uQt1F8ErWYTSCT81t13WeCgE3NKDGB0eDmEncUYqQOr7w8kMFoOZWxp7PRNHGDzqsZXTAmkLvoEwjEnWy/nXrO2ES4xckYR91NofFk6mfCecsWCmM/ZLOC/nRLG2GtHhvWWWkdaMqr7o8/n/YU/0uW3tR4J/D3YtdKgiNA1pROdqXZnIt6+MQO9M2v84BB123LMIeANxv9OyAzL1fZq/7h1hePOUW2gSo2HLOju1wtC2t6d+WuKLuUFB2l9hYj5fJggmVk9O3a25wlzMtP/LQMgQ/kCmrIVqMNSsLPuNXgYFb1tD65qd1zFHFPFoO+caTRoGyDAWO84CyOJGmBuOmkswZk70qtPbDPuHfKSf53lZaIfxAZ0mWGCOB4/UiT7Yy3cx2Q60o2rQTskZExL2dBpExCkRnSTBknrN13UFljBbZ16W9OiN5Q0BUVOcO3JjvGOOr4QCgYVh50cfWONJyiq6xxz/6WNESj6qTYJ7/uRtwhdW9oCOq53ci9q8pYFJ/VSojzNQjjPOyx8N8dtJ019PE6nGiREnd6a0EIU=
  # Github Read-only API Key (for Carthage)
  - secure: h+aeQzBtH+7dd730Ig/dc3Mo95IHykmrsYD6EoazuPWLsxupWjgvbdky2nK1i2+c9eHfG/RJJZRCPqgXUoLBf1exzc93x4864g2qQAMOepMiNtYJQx81g7/Iy3ImkCXLXiTfBXCvKGg8Avi4a5840wZhS4VV9ltxSA9Ws8amPRy6qQPyFJMpUE/RNy9CGabheor2b1cSmQ+9wN5XeI5S+AS0rW2BpuiEVp8JePMCMhtmge197HjUX6xFdwd2Cqb+Xg9lmWYxnO2SlHtVBss7sPjueHbe5rKjdmV/UO8WvSJwptUTyNxc4XN4qrSWuGtxVSLPyLl700FLDYsA4P+d2KZu2I1fhdeS93seVWFwn5qDJY6z9kEtDbvAst7J4eIf9rcy7gBpCqqAw+ibSPMQZvp5oM3/Yswm12hKfA0Dy44s/1M5bC96P8g02s17GoS0UmldYvcHeEJNWzMZToM8BSRaAmAtDg1Gi/1nvB8pOJ9isB++MpfOIDIiBKlE5sxDM+IQPegxgsTo9uf4z3qxd/n6XPmzClBt9z+sn46NEa6g+vQx7RZElKdQWS5wz12Kb6EjnDdOPhtNc6w8z8Opc4CV5mZiq4jmGX48W0+x57l10ZTvlbj3JOSv16H4tXlArGdxQ0QydjQjNXd/sCHiCQwh1IIE+YmqcZXExdcNdag=
